# Azure Pipelines config

jobs:
  - job: test
    strategy:
      matrix:
        linux_node_12:
          image_name: ubuntu-latest
          node_version: 12.x
        linux_node_10:
          image_name: ubuntu-latest
          node_version: 10.x

        # MacOS currently failing. See #1
        # mac:
        #  node_version: 12.x
        #  image_name: macOS-latest

        # Windows not yet supported. See #2
        # windows:
        #  node_version: 12.x
        #  image_name: windows-latest
    pool:
      vmImage: $(image_name)
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: 'Install Node.js $(node_version)'

      - script: npm install
        displayName: 'Install dependencies'

      - script: npm run test:cover
        displayName: 'Run tests'

      - script: npm run docs
        displayName: 'Build docs'

      - script: npm run build
        displayName: 'Build package'

      # Only upload coverage on Linux (fails on Windows and largely
      # unncessary to duplicate by OS anyway)
      - script: bash <(curl -s https://codecov.io/bash)
        condition: and(succeeded(), eq(variables['agent.os'], 'Linux'))
        displayName: 'Upload coverage'

  - job: deploy
    dependsOn: test
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 12.x
        displayName: 'Install Node.js'

      - script: |
          npm install
          # Build docs to ensure that docs folder
          # is present for semantic-release verifyConditions
          npm run docs
          npx semantic-release
        env:
          GIT_AUTHOR_NAME: Stencila CI Bot
          GIT_AUTHOR_EMAIL: ci@stenci.la
          GIT_COMMITTER_NAME: Stencila CI Bot
          GIT_COMMITTER_EMAIL: ci@stenci.la
          GITHUB_TOKEN: $(GITHUB_TOKEN)
          NPM_TOKEN: $(NPM_TOKEN)
        displayName: 'Deploy docs and package'
